# Generated by Django 6.0.3 on 2026-03-28 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('cgpa', models.FloatField()),
                ('skills', models.CharField(max_length=200)),
                ('projects', models.IntegerField()),
                ('internships', models.IntegerField()),
            ],
        ),
    ]
