# Generated by Django 6.0.3 on 2026-03-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='skills',
            new_name='technical_skills',
        ),
        migrations.AddField(
            model_name='student',
            name='aptitude',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='branch',
            field=models.CharField(choices=[('Engineering', 'Engineering'), ('Commerce', 'Commerce'), ('Arts', 'Arts'), ('Others', 'Others')], default='Engineering', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='certifications',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='communication',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='student',
            name='leadership',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='soft_skills',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
